// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: compserv/assessmentresult.proto

package compserv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssessmentResultClient is the client API for AssessmentResult service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssessmentResultClient interface {
	AddAssessmentResult(ctx context.Context, in *Result, opts ...grpc.CallOption) (*Result, error)
}

type assessmentResultClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessmentResultClient(cc grpc.ClientConnInterface) AssessmentResultClient {
	return &assessmentResultClient{cc}
}

func (c *assessmentResultClient) AddAssessmentResult(ctx context.Context, in *Result, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/AssessmentResult/AddAssessmentResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessmentResultServer is the server API for AssessmentResult service.
// All implementations must embed UnimplementedAssessmentResultServer
// for forward compatibility
type AssessmentResultServer interface {
	AddAssessmentResult(context.Context, *Result) (*Result, error)
	mustEmbedUnimplementedAssessmentResultServer()
}

// UnimplementedAssessmentResultServer must be embedded to have forward compatible implementations.
type UnimplementedAssessmentResultServer struct {
}

func (UnimplementedAssessmentResultServer) AddAssessmentResult(context.Context, *Result) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssessmentResult not implemented")
}
func (UnimplementedAssessmentResultServer) mustEmbedUnimplementedAssessmentResultServer() {}

// UnsafeAssessmentResultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssessmentResultServer will
// result in compilation errors.
type UnsafeAssessmentResultServer interface {
	mustEmbedUnimplementedAssessmentResultServer()
}

func RegisterAssessmentResultServer(s grpc.ServiceRegistrar, srv AssessmentResultServer) {
	s.RegisterService(&AssessmentResult_ServiceDesc, srv)
}

func _AssessmentResult_AddAssessmentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessmentResultServer).AddAssessmentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AssessmentResult/AddAssessmentResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessmentResultServer).AddAssessmentResult(ctx, req.(*Result))
	}
	return interceptor(ctx, in, info, handler)
}

// AssessmentResult_ServiceDesc is the grpc.ServiceDesc for AssessmentResult service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssessmentResult_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AssessmentResult",
	HandlerType: (*AssessmentResultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAssessmentResult",
			Handler:    _AssessmentResult_AddAssessmentResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compserv/assessmentresult.proto",
}
